import 'package:flutter/material.dart';
import 'screens/login_screen.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const PolicySimplifierApp());
}

class PolicySimplifierApp extends StatelessWidget {
  const PolicySimplifierApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Policy Simplifier',
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      home: const LoginScreen(),
    );
  }
}
